version: '3'

services:
  katastima_dev:
    build:
      context: .
    volumes:
      - ./public/media:/app/public/media
      - ./public/css:/app/public/css
      - ./public/plugins:/app/public/plugins
      - ./src:/app/src
      - ./public/index.html:/app/public/index.html
      - ./package.json:/app/package.json
    env_file:
      - ./.env
    ports:
      - "3030:3000"
    tty: true
